# Generated by Django 5.0.6 on 2024-05-26 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_news'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentsreg',
            unique_together={('studentId', 'courseId')},
        ),
    ]
