# Generated by Django 5.0.6 on 2024-05-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_studentsreg_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentsreg',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='students',
            name='has_bypassed_prerequisites',
            field=models.BooleanField(default=False),
        ),
    ]
